PA-236/task-initializer
podder-ai/podder-task-base_old pull request #15
Opened 2019-03-21 11:09 UTC by lastshogun13

podder-task-base にTaskInitializerの機能実装をしました

基本的には、下記に書いた仕様通りに実装しています。
https://nexusfrontiertech.atlassian.net/browse/PA-236

特記事項としては以下になります。
・databases/pipeline.py を修正していますが、__init__.pyでContextが初期化されているため、TaskIntializerでもPIPELINE_DATABASE_URLが定義されていないとエラーになるという問題があったのでそれを回避するための処理です。
・将来テンプレート機能など作ることになりそうな気がしたので、task_initializer/buildersの中で拡張しやすいようにしておきました。
・呼び出しは、こんな感じで呼び出すことを想定しています。
　python -m podder_task_base.task_initializer init ${POC_BASE_ROOT}
・バージョン番号は仮で0.1.3にしています。
・version番号を参照できるようにしたいと思い、__init__.pyの中で定義しました。（この実装はdjangoを参考にしています）
・requiments.txt は基本になるものと各タスクによって追加するもの（タスクを書く人が追加する）とがあると思ったので、ここではrequiments.default.txtとしています。

2019-03-21 11:41 UTC, lastshogun13 commented
すみません。自分でバグを見つけたので、レビュー少々お待ちください。
pipeline_framework.proto はテンプレート使って書き換える必要がありました。

2019-03-22 13:52 UTC, lastshogun13 commented
修正したものをプルリクエストに追加しました。

2019-03-25 02:21 UTC, takp requested changes
@lastshogun13 
テストを書ける所は書いておいていただきたいです。特にPublicなインタフェースになる部分のテストをお願いしたいです。

2019-03-25 02:21 UTC, takp commented on setup.py
> +#        'podder_task_base': ['*.txt', '*.sh'],
このコメントは不要そうです

2019-03-25 02:21 UTC, takp commented on podder_task_base/utils/version.py
> +    return '.'.join(str(x) for x in version[:parts])
ここは、 `1.1.0` とかの時に `1.1`  とかって出すためにこんな処理をしてるんですかね？
なるほどー。必要かどうかは別にして、良いと思います。

kubebなんかではそのままtupleではなく、stringでversionを持ってるのでシンプルに出してますね。

2019-03-25 02:21 UTC, takp commented on podder_task_base/task_initializer/builder.py
> +        ]
ここを変更すれば挙動を変えられる感じですね。ありがとうございます

2019-03-25 02:49 UTC, lastshogun13 commented on setup.py
> +#        'podder_task_base': ['*.txt', '*.sh'],
すみません。消し忘れですね。指摘ありがとうございます。

2019-03-25 02:59 UTC, lastshogun13 commented
ユニットテストなのですが、別途issueを立てる話もあったので、まだ書かないでおいたというのがあります。
このissueの中で一緒に対応ということで問題ないのですが、ユニットテストは別途プルリクエストを出すので、問題がなければこの内容にてマージとpypiへの登録をお願いできればと思います。 pypiに登録されたものを使って、この後の作業を進める必要があるもので。

2019-03-25 03:09 UTC, takp commented
@lastshogun13 
おっしゃる通り、今回のスコープ外（元からある機能・クラス等）のUnitテストは別のIssueで対応だと思っています。

今回のIssueで行われた変更や追加されたクラスについてのテストは、今回のIssueの中での対応と思っています。（何か追加や挙動を変更したらテストを書く・修正するのを必須として行く感じです。）

別のプルリクで対応の件、了解です。では、これで一旦マージしてしまいますね。（今回は別のプルリクに影響あるから急ぎって事ですよね？本来はUnitテスト確認してからマージ、PyPI登録が正しい流れなので…）
では、すみませんが、後ほどこのIssueの範囲内で大丈夫なのでUnitテストお願いします。

2019-03-25 03:10 UTC, takp approved these changes

2019-03-25 03:10 UTC, merged

2019-03-25 03:14 UTC, lastshogun13 commented
了解です。
元からある機能へのユニットテストは別issue。本実装関連のユニットテストはこのissue内はその通りですね。
ユニットテストの追加は別のプルリクエストにしようと思いますが、進めておきます。