PA-219/create_podder_task_run
podder-ai/podder-task-base_old pull request #16
Opened 2019-03-26 07:09 UTC by lastshogun13

https://nexusfrontiertech.atlassian.net/browse/PA-205
この件についての修正です。
一部、オプションを短くしたのと一部のファイル入れ忘れ、ミスの修正、ユニットテストの記載などを行なっています。

2019-03-26 07:58 UTC, takp requested changes
@lastshogun13 
Unitテストはそれぞれ追加されたクラスや挙動について作成していただきたいです。 
いくつかテストが追加されていない気がしているのですが、task_initializer/builders 配下の各builder、utilsに追加された file_generator等のUnitテストは別のプルリクになりますでしょうか？

2019-03-26 07:58 UTC, takp commented on tests/task_initializer/test_builder.py
> +        shutil.rmtree(target_dir)
ここでは try/finallyで書かかれてるんですね。
Pytestでは `setup_method` や `teardown_method` などを使ったり、fixtureの機能を使ったりすることで、最初/最後に実行する処理を書けるので、なるべくそのようにしてもらう方が良さそうです。
書き方も色々、クラスだったりメソッドのままで書いたりできます。一度ご確認頂けますでしょうか？

2019-03-26 07:58 UTC, takp commented on tests/task_initializer/test_builder.py
> +        print("--base_set--")
printは残っちゃった感じですか？なるべく削除お願いします

2019-03-27 04:51 UTC, lastshogun13 commented on tests/task_initializer/test_builder.py
> +        print("--base_set--")
ここは意図的にprintを残しました。（）

2019-03-27 14:12 UTC, lastshogun13 commented on tests/task_initializer/test_builder.py
> +        shutil.rmtree(target_dir)
書き直しました。

2019-03-27 14:12 UTC, lastshogun13 commented
builderの中のものについてのテスト追加しました。
file_generatorは使っていないファイルだったので削除しました。

2019-03-28 02:39 UTC, takp commented on tests/task_initializer/test_builder.py
> +        print("--base_set--")
なるほど…これって、 `==` で内容が合ってない時、Pytestが差分を表示してくれませんでしたか？ Pytest実行時に、確か `-v` オプションを付けると出ないですか？

2019-03-28 02:45 UTC, lastshogun13 commented on tests/task_initializer/test_builder.py
> +        print("--base_set--")
はい。確かに-vで結果を表示してくれるんですが、setの中身がある程度大きくなるので、ズレがあった場合にそのまま表示されると何がどう違うのかが非常に読みづらいのです。なので、比較しやすいようにこのprintではソートして表示するようにしています。

2019-03-28 02:46 UTC, takp commented on tests/task_initializer/test_builder.py
> +        print("--base_set--")
そうなんですね。了解しました！

2019-03-28 02:47 UTC, takp approved these changes
LGTM 👍

2019-03-28 02:47 UTC, merged