PA-263/create_podder_init
podder-ai/podder-task-base_old pull request #17
Opened 2019-03-28 15:11 UTC by lastshogun13

https://nexusfrontiertech.atlassian.net/browse/PA-263
podder initの実装のためのプルリクエストです。

以下のようなことを行なっています。
・log.ymlを使わずにconfig/pipeline.ymlを使うようにする
・shutil.copytreeを使ってテンプレートのコピーを行う

2019-03-29 07:35 UTC, takp requested changes

2019-03-29 07:35 UTC, takp commented on podder_task_base/task_initializer/builder.py
>              [MkdirBuilder   , 'error'                              , None],
あ、これが必要なのって、フォルダの中身がないからフォルダが作られない感じですか？
もしそうだったら、 `.gitkeep` とか置いちゃって良いと思うので、それで対処するのはどうでしょうか？
（そうすれば MkdirBuilderは不要にできそうでしょうか）

2019-03-29 07:35 UTC, takp commented on podder_task_base/log/log_setting.py
> +    PIPELINE_YML_PATH = 'config/pipeline.yml'
ここのパスも修正願います 🙏

2019-03-29 07:35 UTC, takp commented on podder_task_base/task_initializer/builder.py
>              [FilecopyBuilder, 'run_codegen.py'                     , self.CHMOD755],
ここで FilecopyBuilderが必要なのってなぜでしょうか？
なるべく FilecopyBuilderも無くしたいと思ったのですが、ファイルの権限でしょうか？

copytreeで権限もコピーできないでしょうか？
もし難しければ、Builderは使わず、権限設定の必要なファイルだけ os.chmod などで一気に変えてしまうのはどうでしょうか？
（このあたり後ほどのリファクタリングの方が良いですかね？？）

2019-03-29 07:35 UTC, takp commented on podder_task_base/task_initializer/builder.py
> +        self.templates_dir = os.path.join(this_dir, "./templates")
os.path.join がつなげてくれるので、 `./templates` => `templates` で大丈夫と思います

2019-04-01 02:08 UTC, lastshogun13 commented
pathの修正（pathlibへの移行）とFilecopyBuilder, MkdirBuilderの使用部分の削除を行いました。（FilecopyBuilder, MkdirBuilder自体の削除はリファクタリング時にしたいなと思いライブラリ自体は残っています）

2019-04-01 08:39 UTC, takp approved these changes
LGTM 👍

2019-04-01 08:39 UTC, merged