WIP: add read only endipoint
podder-ai/podder-task-base_old pull request #29
Opened 2019-05-14 06:25 UTC by ueta-eisuke

2019-05-15 00:41 UTC, ueta-eisuke commented on podder_task_base/context.py
> +        self.ro_session = PipelineROSession()
read用のセッション。

2019-05-15 06:52 UTC, takp requested changes
コメントしました

2019-05-15 06:52 UTC, takp commented on podder_task_base/settings.py
> +PIPELINE_RO_DATABASE_URL = get('PIPELINE_RO_DATABASE_URL')
`RO` => `READ_ONLY` に変更してもらえますか？ 昨日言えば良かったんですが、 省略形はなるべくなくすという方針なので、すみませんがお願いします

2019-05-15 06:52 UTC, takp commented on podder_task_base/databases/pipeline.py
> +    ROSession: DeclarativeMeta = None
Read only のURL (`PIPELINE_RO_DATABASE_URL`) がなければ、 Write のセッションをセットしてあげるのはどうでしょうか？

そうすれば、（ユースケースとして一番多そうな）write もreadも同じエンドポイントという場合に、.env で環境変数は１つだけ( `PIPELINE_DATABASE_URL` ) セットすれば良いのでその方が便利かなと思いました。（あと、後方互換というか、前の設定でも壊れないので）

2019-05-15 06:52 UTC, takp commented on podder_task_base/context.py
> +        self.ro_session = PipelineROSession()
`ro_session` => `read_only_session` というように変更お願いできますか？

2019-05-15 08:26 UTC, ueta-eisuke commented on podder_task_base/context.py
> +        self.ro_session = PipelineROSession()
DONE

2019-05-15 08:26 UTC, ueta-eisuke commented on podder_task_base/settings.py
> +PIPELINE_RO_DATABASE_URL = get('PIPELINE_RO_DATABASE_URL')
DONE

2019-05-15 08:27 UTC, ueta-eisuke commented on podder_task_base/databases/pipeline.py
> +    ROSession: DeclarativeMeta = None
sensorやwriterの.envにも read only の環境変数を追加した方が良いですかね？上の対応で今の設定でも影響はないですが。

2019-05-16 14:08 UTC, takp commented on podder_task_base/databases/pipeline.py
> +    ROSession: DeclarativeMeta = None
あ、確かにそうですね！ぜひお願いしたいです

2019-05-16 14:10 UTC, takp commented on podder_task_base/databases/pipeline.py
> +    ROSession: DeclarativeMeta = None
あ、でも、標準の `.env` には追加する方が良いのかなぁー。ユースケースは多くなさそうだし、一旦標準ではなくても良いかもですね。

↑で追加してほしいと思ったのは、 `cinnamon-podder-saas` の sensor / writer の `.env` でした

2019-05-16 14:11 UTC, takp approved these changes
LGTM 👍

2019-05-16 14:11 UTC, merged