[WIP] Feature/pa 784/add log in podder task base
podder-ai/podder-task-base_old pull request #35
Opened 2019-06-19 10:24 UTC by lastshogun13

今まで、ユーザーが書いたtaskのなかで例外が発生した場合、grpcごと落ちていたのですが、これを例外を受けてエラーログを吐くように直しました。（inputsとexecuteとoutputsにかけています）
inputは打つ手なしな状況なのでFATAL、executeとoutputsはユーザーのコードの分岐によるかもということでERRORとしています。全部FATALでしょ、とかであれば指摘してください。

他はFATAL,ERRORのレベルでログする部分がなさそうだったので特に直していません。

バージョン番号はあげるのが前提かと思いますので、0.3.1にしておきました。

他は、細かいPEP8のコード規約に合わせた修正等になります。

2019-06-19 10:25 UTC, lastshogun13 commented on podder_task_base/log/log_setting.py
>      def load(self):
このファイルの修正は、pycharmの警告に出た物の修正です。
yaml.loadは、警告がでていたのを避けるため、safe_loadに変えています。

2019-06-19 10:27 UTC, lastshogun13 commented on podder_task_base/log/logger.py
pycharmで出ていた警告の修正です。

formatはデフォルトの関数であったので変数名を変えました。level -> log_levelも一緒に直しています。

2019-06-19 10:27 UTC, lastshogun13 commented on podder_task_base/tasks/base_task.py
> +from typing import Any, List
podder-taskに定義されているexecuteのtype hintとずれていたので合わせました。

2019-06-19 10:27 UTC, lastshogun13 commented on requirements.txt
>  jinja2==2.10.1
podder-cliに合わせました。

2019-06-19 10:28 UTC, lastshogun13 commented on setup.py
> +    version='0.3.1',
バージョンを上げました。

2019-06-19 10:29 UTC, lastshogun13 commented on podder_task_base/api/task_api_executor.py
>  import json
ユーザーが書いたコートの例外でgrpcごと落ちるのを防ぐために例外補足し、ログに吐くようにしました。

2019-06-19 10:41 UTC, takaaki-mizuno requested changes

2019-06-19 10:41 UTC, takaaki-mizuno commented on podder_task_base/api/task_api_executor.py
> +
これ、エラーキャッチの処理方法が3つとも一緒で、3行まとめてキャッチしても結果が同じだと思うのですが、分けた意図はなんですか？

2019-06-20 01:18 UTC, ueta-eisuke commented on podder_task_base/api/task_api_executor.py
> +
@lastshogun13 こちら全てerrorでまとめてキャッチしたので良いと思います。タスク内の処理で例外が発生するのは、処理データの結果がおかしいとかがメインなのかなと。Nexus側で即時対応レベルではないと思っています。（以下のログの定義もerrorになっています。）
https://docs.google.com/spreadsheets/d/1-KXUtqtTt_ImBl4EH3legDIGi9O_r_igUdisqcdnzfI/edit#gid=1825772335

2019-06-20 02:16 UTC, lastshogun13 commented on podder_task_base/api/task_api_executor.py
> +
エラーレベル分けるかもくらいの理由で分けていました。
こちらerrorレベルでまとめて処理するように直します。

2019-06-20 03:17 UTC, takp commented on podder_task_base/api/task_api_executor.py
> +        task_response.dag_id = "ERROR_DAG_ID"
`ERROR_DAG_ID` というのを使っているのはなぜですか？
DAG_ID は取得できないんでしたっけ？

2019-06-20 03:17 UTC, takp commented on setup.py
> +    version='0.3.1',
バージョンの定義は１箇所にしたいので、 `__init__.py` を参照して取得するようにしたいです

2019-06-20 03:17 UTC, takp commented on podder_task_base/__init__.py
> +VERSION = (0, 3, 1)
今回の変更は、ブレーキングチェンジを含みますか？
あと、仮にマイナーバージョンを上げる場合は、 `0.3.1` ではなく次は `0.3.0` かなと思うのですがどうでしょうか。

2019-06-20 03:44 UTC, ueta-eisuke commented
@lastshogun13 ログレベルを追加したファイルが入っていなさそうなのですが、漏れていますか？

2019-06-20 03:58 UTC, takp commented on podder_task_base/__init__.py
> +VERSION = (0, 3, 1)
あ、もともとすでに `0.3.0` だったんですね。了解です。
バージョンの定義はここの `__ini__.py` 一箇所に定義するようにしましょう〜。（複数箇所はあるのは間違いの元なので…）

2019-06-20 04:02 UTC, lastshogun13 commented on podder_task_base/__init__.py
> +VERSION = (0, 3, 1)
ブレーキングチェンジは含まないです。　0.2.0 になっていたのは上げ忘れになっていたようです。

2019-06-20 04:04 UTC, lastshogun13 commented on podder_task_base/api/task_api_executor.py
> +        task_response.dag_id = "ERROR_DAG_ID"
inputsの解析部分（_convert_to_input_dataメソッド）でエラーになっている可能性もあるので、その場合はdag_idが取得できなくなるかなと思い、エラーが明確になる固定値を入れました。

2019-06-20 09:29 UTC, takp commented on podder_task_base/api/task_api_executor.py
> +        task_response.dag_id = "ERROR_DAG_ID"
@lastshogun13 エラーとは関係なく、dag_id は、 16行目の `dag_id = request.dag_id` で取得できてるんじゃないですかね？

2019-06-20 09:29 UTC, lastshogun13 commented
指摘点を修正しました。
ログレベルを追加したファイルについては、以下のプルリクエストのpipeline.ymlになります。
https://github.com/podder-ai/cinnamon-podder-saas/pull/72

2019-06-20 09:42 UTC, lastshogun13 commented
criticalレベル追加しました。

2019-06-20 09:49 UTC, ueta-eisuke commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
criticalではなくfatalですね。

2019-06-20 09:50 UTC, ueta-eisuke commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
あと明日のかわぐちさんへの確認次第では、warningもwarnでラップした方が良いかもです。

2019-06-20 09:53 UTC, lastshogun13 commented
pythonだと元が、ciriticalというレベル名なので、fatalというメソッドをcriticalのエイリアスとして使えるようにしました。

2019-06-21 04:59 UTC, lastshogun13 commented on podder_task_base/api/task_api_executor.py
> +        task_response.dag_id = "ERROR_DAG_ID"
これは、grpcできたデータが破損していた場合（https://nexusfrontiertech.atlassian.net/browse/PA-811 のようなケース）を心配していたのですが、その前に取得しているし、grpcの仕様を確認すると破損した場合はパースエラーになるようなので、request.dag_idが必ず取得できる前提で大丈夫そうですね。
というわけで修正しました。

2019-06-21 06:12 UTC, lastshogun13 commented on setup.py
>  from setuptools import setup, find_packages
プルリクエストが混ざってしまって恐縮なのですが、
やろうとおもって後回しになっていた、setup.pyとrequiments.txtの両方にライブラリ情報を持っているのを、片方にまとめる件をやっておきました。

2019-06-21 08:14 UTC, takp commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
@lastshogun13 これは確認済みでしょうか？

2019-06-21 08:18 UTC, lastshogun13 commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
はい。 今は、pythonデフォルトのcritical、warningという名称は生きにして、以下のようにエイリアスとして使えるようにしています。
fatal -> critical
warn -> warning
trace -> notset

2019-06-21 08:20 UTC, takp approved these changes
LGTM

2019-06-21 08:21 UTC, ueta-eisuke commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
あれ？いつ確認しましたか？把握していないのですが。

2019-06-21 08:24 UTC, ueta-eisuke commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
@lastshogun13

2019-06-21 08:29 UTC, lastshogun13 commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
「確認」という言葉を、「この件の修正対応をしたか」という意味合いで捉えて、修正済みという意味で「はい」と回答していました。
@eisuke 上記のエイリアスのメソッドが作ったという対応で、大丈夫ですか？

2019-06-21 08:33 UTC, ueta-eisuke commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
あ、今回のログ対応が、cinnamon-saasか、podderとしての対応化を、かわぐちさんと認識を合わせようとのことだったので、みなみさん確認お願いしても良いですか？

2019-06-21 08:45 UTC, lastshogun13 commented
変数名をfpからfileにしておきました。

2019-06-21 09:17 UTC, lastshogun13 commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
了解です。

2019-06-21 09:40 UTC, lastshogun13 commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
川口さんからの回答としては、
https://docs.google.com/spreadsheets/d/1-KXUtqtTt_ImBl4EH3legDIGi9O_r_igUdisqcdnzfI/edit#gid=1825772335
のログレベルの定義自体は、cinnamonスペシフィックではなく、podder全体として今後使っているものとのこと。

現状のエイリアスを使っての実装自体は問題ないとのこと。

2019-06-24 03:22 UTC, lastshogun13 commented
@takp @ueta-eisuke こちら川口さんに仕様の確認も取れたのマージで大丈夫でしょうか？

2019-06-24 03:25 UTC, takp commented
@ueta-eisuke OKならApproveお願いしますー

2019-06-24 04:58 UTC, ueta-eisuke commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
ログレベルは、以下なので、他の不要なのは削除したいです。（warningとcritical）
- fatal
- error
- warn
- info
- debug
- trace

2019-06-24 05:45 UTC, lastshogun13 commented on podder_task_base/log/logger.py
> +    def critical(self, msg, *args, **kwargs):
了解です。

2019-06-24 05:49 UTC, lastshogun13 commented
criticalとwarningを削除しておきました。
後ほど、以下のプルリクエストの方も直しておきます。
https://github.com/podder-ai/cinnamon-podder-saas/pull/72

2019-06-24 05:51 UTC, eisuke-ueta approved these changes
LGTM

2019-06-24 08:46 UTC, lastshogun13 commented
二人のapprovalが出たのでマージしておきます。

2019-06-24 08:46 UTC, merged