PA-851 replace newline character
podder-ai/podder-task-base_old pull request #41
Opened 2019-07-05 08:47 UTC by TomokoUe

https://nexusfrontiertech.atlassian.net/browse/PA-851

背景
  Podderタスクが生成したログに改行が入っていて、Fluentdで収集すると、キレイに1レコードとして判断できないのです。
  Fluentdにうまく複数行の対応ができたら、必要ですが、すぐ解決できなさそうなのです。

やりたいこと
  Loggerクラスで改行があったら、 \n などに変換する

2019-07-05 08:49 UTC, TomokoUe commented
質問：47行目、ログレベルの設定が内容に見えるがOK？

2019-07-05 09:10 UTC, takp requested changes
@TomokoUe いま気づいたんですが、この podder-task-base 今見たら全然テスト追加されてないですね... 😨（このリポジトリだけ手が回ってなかったやつだと思います...） 
今回の変更部分についてだけで良いので、ユニットテストを追加してもらえないでしょうか？

[podder-cli](https://github.com/podder-ai/podder-cli/tree/develop/tests/unit) などを参考にして、書いて頂けると助かります。他にテストがないので分かりにくいと思うので、何か迷ったら聞いてください

2019-07-05 09:14 UTC, TomokoUe commented
@takp 
そうだ、ユニットテスト！mikeさんから聞いてたのに都合よく忘れてました。まず色々調べたり見てみます。

2019-07-05 09:15 UTC, takp commented on podder_task_base/log/logger.py
> +        self.logger.log(self._convert_newline_character(msg), extra=self._create_extra(), *args, **kwargs)
確かにここ、ログレベルの設定必須っぽいですね… https://docs.python.org/3/library/logging.html#logging.Logger.log

この `log` メソッド呼ぶとエラーになりますでしょうか？調べて頂いて、必要そうなら修正お願いしたいです

2019-07-05 09:18 UTC, tuantranf commented
確認しました、問題なさそうです。
Logger周りのUnitテストの追加をお願いします。

2019-07-05 09:18 UTC, TomokoUe commented on podder_task_base/log/logger.py
> +        self.logger.log(self._convert_newline_character(msg), extra=self._create_extra(), *args, **kwargs)
呼び出したらエラーになっています。

> 調べて頂いて、必要そうなら修正お願いしたいです

承知しました。

2019-07-05 09:19 UTC, TomokoUe commented
mikeさんコメントありがとうございます。Unitテスト書いてみます。

2019-07-05 09:37 UTC, takaaki-mizuno approved these changes
`_convert_newline_character` という特定の意図を持ったフィルタ処理を、fatal、errorと全部から呼び出すのはあまり良くない気がする。今後別のフィルタを追加したときに、また全部の箇所を変えなくてなはらないから。
メッセージを前処理するメソッドを定義し、ログ系関数からはそれを呼び出し、そのなかで ` `_convert_newline_character`が呼び出される方がいい気がする

2019-07-05 11:01 UTC, TomokoUe commented
なるほど、そのほうが断然良いですね。挑戦してみます。

2019-07-09 09:40 UTC, takp commented on podder_task_base/log/logger.py
> +        if old_character in msg:
ひょっとして、ここの条件分岐って必要ないのでは？と思いました

2019-07-09 09:40 UTC, takp commented on tests/unit/log/test_logger.py
> +        pass
ここと `test_log` ってテスト追加し忘れてないでしょうか？

2019-07-09 10:02 UTC, TomokoUe commented on tests/unit/log/test_logger.py
> +        pass
@takp 
ログレベルがinfo以上に設定されてるので（テストも）、実行エラーにならない事だけ確認できてればいいのかなと思い、呼び出しだけして内容は確認していない状況です。
unitテストのログレベル変えて確認入れた方がいいですかね？

2019-07-09 10:24 UTC, takaaki-mizuno requested changes

2019-07-09 10:24 UTC, takaaki-mizuno commented on podder_task_base/log/logger.py
> +    def _log(self, lvl, msg, *args, **kwargs):
_log だと何をしているのかわからないから、 _format とかのほうが良さげ

2019-07-09 10:55 UTC, TomokoUe commented on podder_task_base/log/logger.py
> +    def _log(self, lvl, msg, *args, **kwargs):
この関数は、ログの形成をする役割。確かにその通りです。変更します。

2019-07-10 06:21 UTC, TomokoUe commented
@takp @takaaki-mizuno 
修正しました。ご確認ください。

2019-07-10 09:04 UTC, takp commented on tests/unit/log/test_logger.py
> +        pass
@TomokoUe 遅くなっってすみません。
ついでなので、そこもできればテスト追加できますでしょうか？ `setup` / `teardown` メソッドを使うとテスト開始前と後に処理を追加できるので、このテストの時だけログレベル変えてもらうとかが良いかもです (参考： https://github.com/podder-ai/podder-cli/blob/develop/tests/unit/deploy/test_version_set_manager.py#L29-L34 )

2019-07-10 09:11 UTC, TomokoUe commented on tests/unit/log/test_logger.py
> +        pass
> このテストの時だけログレベル変えてもらうとかが良いかもです

それ、いいですね。やってみます。

2019-07-11 06:57 UTC, takp approved these changes
LGTM

- TRACEレベルのログはバグが見つかったので、別途対応する方針

2019-07-12 04:17 UTC, takaaki-mizuno approved these changes

2019-07-12 04:17 UTC, takaaki-mizuno commented
LGTM

2019-07-12 04:25 UTC, merged